name: "build packages"

on:
  release:
    types: [published]
    branches:
      - 'master'

jobs:
  react-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: install node v14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          scope: '@uninow'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}